### ISSUE TITLE
V0.3 Todos

### ISSUE THREAD

**Issue by tsoonjin** [cs2103aug2015-w15-3j/main#104]
## Todos
- [x] Use task name in feedback message. Set a limit to length of name #109
- [x] Not intuitive exception message like "Failed to parse". #99  
- [x] Addition of task to displayed view should follow an intuitive manner like always add to bottom. #82 
- [ ] improve search command runner #105 
- [x] easy way for user to change to different views #108 
- [x] set directory supports relative path and test more on windows path #110

**Comment by LingJie-Zhu** [comment]
For 3.: Using task IDs for the message when deleting multiple tasks due to limited space for task names

**Comment by tsoonjin** [comment]
The feedback can will expand accordingly . Just inset newline to separate the message

**Comment by LingJie-Zhu** [comment]
Todo:
- Improve batch/done feedback messages to that of batch add.
- Change Edit's feedback message to reflect input's id instead of task's id as they might be different
- display "all/float/floating/overdue/completed/pending/etc"
