### ISSUE TITLE
V0.4 Todos 

### ISSUE THREAD

**Issue by tsoonjin** [cs2103aug2015-w15-3j/main#123]
## Aim
- Provide more useful feedback for user such as free time slot 
- More powerful search that includes duration of time within a specific date 
- Support for natural date input 
- Refactor existing code base 
## Todo
- [x] better help cheat sheet 
- [x] guidance on feedback bar as user type a command 
- [x] ~~include tags on sidebar~~ 
- [x] Scroll using page down and page up 
- [x] ~~uses default view whenever a changes occur~~ 
- [x] search case insensitive
