### ISSUE TITLE
Improvement to current display format 

### ISSUE THREAD

**Issue by tsoonjin** [cs2103aug2015-w15-3j/main#82]
## Features:
- [x] proper padding and fix a limit to length of task name 
- [x] color coding task based on priority 
- [x] sorted based on dates
- [x] show a good balance of tasks from today, tomorrow, next week 
- [x] find a way to include `overdue tasks` and `floating tasks`
- [x] changes to display view after executing a command should be consistent and logical
